In [ ]:
!nvidia-smi

Thu Apr 16 19:22:02 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


**Introduction to tensor**

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix = torch.tensor(  [[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#tensor
tensor = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
tensor.shape

torch.Size([3, 3])

In [ ]:
tensor[0]

tensor([1, 2, 3])

# Random Tensors
why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbersto better represent the data.

In [ ]:
# create a random tensors


random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4087, 0.5494, 0.5560, 0.4193],
        [0.5708, 0.4159, 0.8808, 0.2297],
        [0.9963, 0.3571, 0.2379, 0.2511]])

In [ ]:
# create a random tensors with similar shape to an image

random_image_size_tensor = torch.rand(size =(3,224,224) )# height, width,colour channel
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#Zeros and Ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create atensors of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

#Creating a range of tensors and tensors-like

In [ ]:
#use torch.range
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start=0, end =10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#creating like-tensor
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##tensor data type

**Note:** Tensor datatype is one of the 3 big errors issue with pytorch & deep learning:
1.Tensors not right datatype
2.Tensors not right shape
3.Tensors not on the right deevice

In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device =None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor  = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

## getting information from tensor

In [ ]:
#crteate a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0654, 0.5061, 0.9748, 0.1315],
        [0.5770, 0.3656, 0.5843, 0.9181],
        [0.7111, 0.8347, 0.9125, 0.9849]])

In [ ]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Device of tensor:{some_tensor.device}")

tensor([[0.0654, 0.5061, 0.9748, 0.1315],
        [0.5770, 0.3656, 0.5843, 0.9181],
        [0.7111, 0.8347, 0.9125, 0.9849]])
Datatype of tensor:torch.float32
Device of tensor:cpu


In [ ]:
some_tensor.size()

torch.Size([3, 4])

##manipulating tensors(tensor operations)

Tensor operation includes
1. addition
2.substruction
3.multiplication
4.division
5.matrix multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
#substruct 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
#try out pytorch in-built function
torch.mul(tensor,10)


tensor([10, 20, 30])

##Matrix multiplication

Two main ways of performing multiplication in neural network and in deep learning.
1.Element wise multiplication
2.Matrix multiplication(dot product)

In [ ]:
# element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor} ")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9]) 


In [ ]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]

  print(value)

tensor(1)
tensor(5)
tensor(14)
CPU times: user 1.41 ms, sys: 0 ns, total: 1.41 ms
Wall time: 1.68 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 472 µs, sys: 0 ns, total: 472 µs
Wall time: 550 µs


tensor(14)

## one of the most error in deep learning: shape errors

In [ ]:
# shapes for marrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6] ])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
torch.mamul(tensor_A, tensor_B)

AttributeError: module 'torch' has no attribute 'mamul'

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [ ]:
 # the matrix multiplication operation works when tensor_B is transposed
print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.shape}")
print(f"multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension must match")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\noutput shape: {output.shape}")

Original shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([3, 2])
multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension must match
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

output shape: torch.Size([3, 3])


## Finding tensor aggregation(mean, max, min, sum)

In [ ]:
# creat a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function requires a float dtype

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max.

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
#finding the positional tensor that has maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

##Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor of a defined shape.

In [ ]:
#lest's create tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - remove all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

# Remove extra dimensionsfrom x_reshaped
x_squeezed = x_reshaped.squeeze()

print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a sppecific dim(dimension)
print(f"previous target: {x_squeezed} ")
print(f"previous shape: {x_squeezed.shape}")
# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)

print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 
previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [ ]:
# torch.permute - rearrange the dimension of t=a target tensor in a specified order
x_original = torch.rand(size =(224, 224, 3))

# permute the original tensor to rearrange the axis( or dim) order
x_permuted = x_original.permute(2, 0, 1)
print(f"previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original

tensor([[[0.6833, 0.5557, 0.1427],
         [0.9308, 0.8844, 0.9568],
         [0.0692, 0.7452, 0.2895],
         ...,
         [0.6332, 0.2962, 0.1997],
         [0.7339, 0.7011, 0.4523],
         [0.5635, 0.9703, 0.9138]],

        [[0.4221, 0.0910, 0.4299],
         [0.4804, 0.7345, 0.4472],
         [0.5416, 0.6417, 0.2215],
         ...,
         [0.6959, 0.6240, 0.5928],
         [0.6391, 0.7982, 0.3948],
         [0.4154, 0.0239, 0.7691]],

        [[0.6383, 0.2551, 0.6346],
         [0.8272, 0.4427, 0.1972],
         [0.1729, 0.6133, 0.3316],
         ...,
         [0.8997, 0.0404, 0.0304],
         [0.1624, 0.8495, 0.5870],
         [0.2792, 0.9183, 0.1703]],

        ...,

        [[0.5895, 0.1088, 0.3453],
         [0.6589, 0.0352, 0.3595],
         [0.8009, 0.2085, 0.6288],
         ...,
         [0.1676, 0.1418, 0.7370],
         [0.6324, 0.0032, 0.4272],
         [0.0658, 0.7744, 0.8535]],

        [[0.2454, 0.5969, 0.0209],
         [0.7060, 0.3102, 0.4367],
         [0.

## Indexing (Selecting data from tensors)
* Indexing with Pytorch is similar indexing with Numpy.

In [ ]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Les's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Les's index the middel bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# let's index on the most inner bracket (last dimmension)
x[0][1][1]

tensor(5)

In [ ]:
# you can also use " : " to select all the target dimmension
x[ :, 0 ]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0ths and 1st dimension but only index 1 and 2nd dimeension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# index on x return 9
print(x[0][2][2])

# index on x return 3,6,9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## Pytorch Tensor and Numpy

* Numpy is a popular python scientific computing library.
and because of this , pytorch has functionality intract with it.


In [ ]:
# Numpy in array in tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# change the value of array , what will be the do "Tensor?"
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor, what happens to "numpy_tensor"
tensor = tensor+1

tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to make random out of random)

In [ ]:
torch.rand(3, 3)

tensor([[0.6685, 0.9654, 0.7760],
        [0.1765, 0.4196, 0.7126],
        [0.9323, 0.6116, 0.8942]])

In [ ]:
import torch
# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6569, 0.2738, 0.8185, 0.9500],
        [0.8577, 0.6017, 0.6519, 0.1381],
        [0.1748, 0.7348, 0.8723, 0.5537]])
tensor([[0.4282, 0.5905, 0.4817, 0.8534],
        [0.9279, 0.2289, 0.2585, 0.5666],
        [0.7136, 0.5549, 0.7969, 0.3665]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random bur reproducibile tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and Pytoch objects on the GPU (and makining faster computations)

In [ ]:
!nvidia-smi

Thu Apr 16 19:32:39 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# check for GPU access for Pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors ( and modules) on the cpu

In [ ]:
# create a tensor
tensor = torch.tensor([1,2,3])
# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## 4.Moving tensors back to the CPU

In [ ]:
# if tensors on GPU , can;t transform it to numpy
tensor_on_gpu()



TypeError: 'Tensor' object is not callable

In [ ]:
# to fix the GPU tensor with numpy issue , we can first aet is to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## exercises and extra_curricullum

In [ ]:
torch.rand(7, 7)

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])